services:
  # Frontend folder nog te vervolledigen
  frontend:
    build: ./Frontend
    container_name: frontend
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`sokrates.traefik.me`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls=true"
      - "traefik.http.services.frontend.loadbalancer.server.port=4200"
    networks:
      - gateway
      - backend
      - frontend
  
  backend:
    build: ./Backend
    container_name: backend
    restart: unless-stopped
    depends_on:
      database:
        condition: service_healthy
    env_file: Env/db.env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`nest.sokrates.traefik.me`)"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls=true"
      - "traefik.http.services.backend.loadbalancer.server.port=3000"
    networks:
      - gateway
      - backend

  database:
    image: postgres:16-alpine
    container_name: database
    restart: unless-stopped
    # Dit is om te controleren of de database goed werkt.
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U data_user -d data_inventory"]
      interval: 10s
      retries: 5
      start_period: 15s
    networks:
      - backend
    env_file: Env/db.env
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    depends_on:
      database:
        condition: service_healthy
    networks:
      - backend
      - gateway
    env_file: Env/pgadmin.env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pgadmin.rule=Host(`database.sokrates.traefik.me`)"
      - "traefik.http.routers.pgadmin.entrypoints=websecure"
      - "traefik.http.routers.pgadmin.tls=true"
      - "traefik.http.services.pgadmin.loadbalancer.server.port=80"

  python_container:
    build: ./Scripts
    container_name: python_container
    restart: unless-stopped
    depends_on:
      database:
        condition: service_healthy
    networks:
      - backend
      - api
    env_file: Env/api_keys.env

networks:
  gateway:
    external: true
  backend:
    internal: true
  frontend:
  api:

volumes:
  db-data:
  pgadmin-data: