services:
  frontend:
    build: ./frontend
    container_name: frontend
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`91.99.191.71`)"
      - "traefik.http.routers.frontend.entrypoints=web"
      - "traefik.http.services.frontend.loadbalancer.server.port=4200"
    networks:
      - gateway
      - backend
      - frontend

  backend:
    build: ./backend
    container_name: backend
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`91.99.191.71`) && PathPrefix(`/api`)"
      - "traefik.http.routers.backend.entrypoints=web"
    networks:
      - gateway
      - backend

  database:
    image: postgres:16-alpine
    container_name: database
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U data_user -d data_inventory"]
      interval: 10s
      retries: 5
      start_period: 10s
    networks:
      - backend
    env_file: db.env
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    depends_on:
      database:
        condition: service_healthy
    networks:
      - backend
      - gateway
    env_file: pgadmin.env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pgadmin.rule=Host(`91.99.191.71`) && PathPrefix(`/pgadmin`)"
      - "traefik.http.routers.pgadmin.entrypoints=web"
      - "traefik.http.services.pgadmin.loadbalancer.server.port=80"
      - "traefik.http.middlewares.pgadmin-strip.stripprefix.prefixes=/pgadmin"
      - "traefik.http.routers.pgadmin.middlewares=pgadmin-strip"

networks:
  gateway:
    external: true
  backend:
    internal: true
  frontend:

volumes:
  db-data:
  pgadmin-data: